server:
  port: 9090

spring:
  redis:
    database: 1
    host: localhost
    port: 6379
    password: redis
    timeout: 60s
    jedis:
      pool:
        max-active: -1
        max-idle: 15
        max-wait: -1s
        min-idle: 5
